# Nombre de la aplicación Spring Boot
spring.application.name=web

# Configuración de Thymeleaf para cargar plantillas HTML desde src/main/resources/templates
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuración de la base de datos MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/mecatools?useSSL=false
spring.datasource.username=root
spring.datasource.password=1203128579

# Actualiza automáticamente el esquema de la base de datos al iniciar la app y muestra en consola las consultas SQL ejecutadas por Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
